export type Bailleur =
  | "BM"
  | "BAD"
  | "PNUD"
  | "UE"
  | "AFD"
  | "GIZ"
  | "USAID"
  | "UNICEF"
  | "BOAD"
  | "Gouvernement"
  | "Autre";
export type Pays =
  | "Sénégal"
  | "Côte d'Ivoire"
  | "Mali"
  | "Burkina Faso"
  | "Ghana"
  | "Guinée"
  | "Bénin"
  | "Togo"
  | "Niger"
  | "Mauritanie";
export type Secteur =
  | "Santé"
  | "Education"
  | "Infrastructure"
  | "Agriculture"
  | "Numérique"
  | "Environnement"
  | "Gouvernance"
  | "Eau et Assainissement"
  | "Autre";
export type TypeMarche = "Travaux" | "Services" | "Fournitures" | "Consulting";

export interface AO {
  id: string;
  titre: string;
  bailleur: Bailleur;
  pays: Pays;
  secteur: Secteur;
  type: TypeMarche;
  deadline: string; // ISO
  publication: string;
  montant?: string;
  langue: string;
  contact: string;
  description: string;
  exigences: string[];
  documents: string[];
  source: string;
}

const daysFromNow = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
};

export const BAILLEUR_COLORS: Record<Bailleur, string> = {
  BM: "bg-blue-100 text-blue-900 border-blue-200",
  BAD: "bg-emerald-100 text-emerald-900 border-emerald-200",
  PNUD: "bg-sky-100 text-sky-900 border-sky-200",
  UE: "bg-indigo-100 text-indigo-900 border-indigo-200",
  AFD: "bg-rose-100 text-rose-900 border-rose-200",
  GIZ: "bg-amber-100 text-amber-900 border-amber-200",
  USAID: "bg-red-100 text-red-900 border-red-200",
  UNICEF: "bg-cyan-100 text-cyan-900 border-cyan-200",
  BOAD: "bg-teal-100 text-teal-900 border-teal-200",
  Gouvernement: "bg-slate-200 text-slate-900 border-slate-300",
  Autre: "bg-muted text-foreground border-border",
};

export const MOCK_AOS: AO[] = [
  {
    id: "ao-001",
    titre: "Construction de 12 centres de santé communautaires en milieu rural",
    bailleur: "BM",
    pays: "Sénégal",
    secteur: "Santé",
    type: "Travaux",
    deadline: "2026-07-12T23:59:59.000Z",
    publication: "2026-05-20T00:00:00.000Z",
    montant: "4 200 000 000 FCFA",
    langue: "Français",
    contact: "passation.marches@sante.gouv.sn",
    description: "Construction et équipement de 12 centres de santé communautaires dans Tambacounda, Kédougou et Matam, avec systèmes solaires.",
    exigences: ["Expérience ≥ 8 ans en infrastructures sanitaires","≥ 3 projets similaires en Afrique de l'Ouest","Chiffre d'affaires ≥ 2 Md FCFA/an","Équipe technique permanente"],
    documents: ["Dossier administratif (NINEA, quitus fiscal)","Références techniques","Méthodologie d'exécution","Cautionnement 2%"],
    source: "https://www.armp.sn/",
  },
  {
    id: "ao-002",
    titre: "Étude de faisabilité — Plateforme numérique pour PME agricoles",
    bailleur: "BAD",
    pays: "Côte d'Ivoire",
    secteur: "Numérique",
    type: "Consulting",
    deadline: "2026-08-04T23:59:59.000Z",
    publication: "2026-06-01T00:00:00.000Z",
    montant: "180 000 000 FCFA",
    langue: "Français",
    contact: "tenders@afdb.org",
    description: "Étude de faisabilité technique, économique et financière pour plateforme numérique reliant coopératives et acheteurs régionaux.",
    exigences: ["Cabinet avec expertise numérique et agricole","Études de marché en zone UEMOA","Équipe IT, agro-économie, finance"],
    documents: ["CV équipe clé","Offre technique","Offre financière","Lettre de soumission"],
    source: "https://www.afdb.org/en/projects-and-operations/procurement",
  },
  {
    id: "ao-003",
    titre: "Programme de formation des jeunes au numérique — 5 000 bénéficiaires",
    bailleur: "UE",
    pays: "Mali",
    secteur: "Education",
    type: "Services",
    deadline: "2026-09-15T23:59:59.000Z",
    publication: "2026-06-10T00:00:00.000Z",
    montant: "1 500 000 000 FCFA",
    langue: "Français",
    contact: "delegation-mali@eeas.europa.eu",
    description: "Conception et déploiement d'un programme de formation aux métiers du numérique pour 5 000 jeunes dans 4 régions.",
    exigences: ["Organisation ≥ 5 ans","Capacité ≥ 1000 bénéficiaires","Présence locale ou partenariat"],
    documents: ["PADOR enregistré","Cadre logique","Budget détaillé","CV équipe"],
    source: "https://webgate.ec.europa.eu/europeaid/online-services/",
  },
  {
    id: "ao-004",
    titre: "Réhabilitation de 80 km de pistes rurales — Hauts-Bassins",
    bailleur: "AFD",
    pays: "Burkina Faso",
    secteur: "Infrastructure",
    type: "Travaux",
    deadline: "2026-06-25T23:59:59.000Z",
    publication: "2026-05-02T00:00:00.000Z",
    montant: "3 800 000 000 FCFA",
    langue: "Français",
    contact: "tenders.bf@afd.fr",
    description: "Réhabilitation, ouvrages d'art et signalisation sur 80 km de pistes rurales.",
    exigences: ["Entreprise TP classée ≥ T4","Parc matériel propre","≥ 50 km de pistes réalisées"],
    documents: ["Dossier administratif","Cautionnement","Planning détaillé"],
    source: "https://afd.dgmarket.com/",
  },
  {
    id: "ao-005",
    titre: "Assistance technique — Renforcement de la gouvernance locale",
    bailleur: "PNUD",
    pays: "Niger",
    secteur: "Gouvernance",
    type: "Consulting",
    deadline: "2026-07-28T23:59:59.000Z",
    publication: "2026-05-30T00:00:00.000Z",
    montant: "320 000 000 FCFA",
    langue: "Français",
    contact: "procurement.ne@undp.org",
    description: "Appui aux 12 communes pilotes en planification, budgétisation participative et redevabilité.",
    exigences: ["Expertise décentralisation","Français + langues locales","Présence ou réseau au Niger"],
    documents: ["Note méthodologique","CV experts","Offre financière"],
    source: "https://procurement-notices.undp.org/",
  },
  {
    id: "ao-006",
    titre: "Fourniture d'équipements solaires pour 200 écoles primaires",
    bailleur: "GIZ",
    pays: "Ghana",
    secteur: "Education",
    type: "Fournitures",
    deadline: "2026-08-20T23:59:59.000Z",
    publication: "2026-05-25T00:00:00.000Z",
    montant: "950 000 000 FCFA",
    langue: "Anglais",
    contact: "tenders-ghana@giz.de",
    description: "Livraison et installation de kits solaires (panneaux, batteries, LED) pour 200 écoles rurales.",
    exigences: ["Fournisseur agréé solaire","Garantie ≥ 5 ans","SAV et formation locale"],
    documents: ["Fiches techniques","Certifications IEC","Plan logistique"],
    source: "https://www.giz.de/en/worldwide/333.html",
  },
  {
    id: "ao-007",
    titre: "Appui à la chaîne de valeur cacao — Coopératives de l'Ouest",
    bailleur: "Gouvernement",
    pays: "Côte d'Ivoire",
    secteur: "Agriculture",
    type: "Services",
    deadline: "2026-07-05T23:59:59.000Z",
    publication: "2026-04-28T00:00:00.000Z",
    montant: "640 000 000 FCFA",
    langue: "Français",
    contact: "contact@anrmp.ci",
    description: "Accompagnement de 40 coopératives cacaoyères : structuration, certification, accès marchés internationaux.",
    exigences: ["Expérience cacao","Maîtrise UTZ/Rainforest Alliance"],
    documents: ["Méthodologie","Références","Budget"],
    source: "https://www.anrmp.ci/",
  },
  {
    id: "ao-008",
    titre: "Étude environnementale stratégique du bassin du fleuve Sénégal",
    bailleur: "BM",
    pays: "Mauritanie",
    secteur: "Environnement",
    type: "Consulting",
    deadline: "2026-08-12T23:59:59.000Z",
    publication: "2026-06-02T00:00:00.000Z",
    montant: "420 000 000 FCFA",
    langue: "Français",
    contact: "wb-mauritania@worldbank.org",
    description: "Évaluation environnementale stratégique du bassin du fleuve Sénégal côté mauritanien.",
    exigences: ["Bureau d'études environnementales","Experts seniors"],
    documents: ["Note de cadrage","CV","Offre financière"],
    source: "https://www.worldbank.org/en/projects-operations/products-and-services/brief/procurement-new-framework",
  },
  {
    id: "ao-009",
    titre: "Digitalisation des registres de l'état civil",
    bailleur: "PNUD",
    pays: "Bénin",
    secteur: "Numérique",
    type: "Services",
    deadline: "2026-09-10T23:59:59.000Z",
    publication: "2026-06-05T00:00:00.000Z",
    montant: "780 000 000 FCFA",
    langue: "Français",
    contact: "procurement.bj@undp.org",
    description: "Numérisation et indexation de 2 millions de registres, base nationale sécurisée.",
    exigences: ["Expertise GED","ISO 27001"],
    documents: ["Offre technique","Offre financière"],
    source: "https://procurement-notices.undp.org/",
  },
  {
    id: "ao-010",
    titre: "Construction d'un centre logistique à Lomé",
    bailleur: "BAD",
    pays: "Togo",
    secteur: "Infrastructure",
    type: "Travaux",
    deadline: "2026-08-30T23:59:59.000Z",
    publication: "2026-05-18T00:00:00.000Z",
    montant: "5 100 000 000 FCFA",
    langue: "Français",
    contact: "togo-tenders@afdb.org",
    description: "Hub logistique de 12 ha : entrepôts, voies d'accès, zone douanière au Port de Lomé.",
    exigences: ["Classe T5","Référence portuaire obligatoire"],
    documents: ["Cautionnement 3%","Planning","Dossier technique"],
    source: "https://www.afdb.org/en/projects-and-operations/procurement",
  },
  {
    id: "ao-011",
    titre: "Programme nutrition infantile en milieu scolaire",
    bailleur: "UE",
    pays: "Guinée",
    secteur: "Santé",
    type: "Services",
    deadline: "2026-06-30T23:59:59.000Z",
    publication: "2026-05-08T00:00:00.000Z",
    montant: "1 100 000 000 FCFA",
    langue: "Français",
    contact: "delegation-guinee@eeas.europa.eu",
    description: "Distribution de repas équilibrés à 80 000 enfants sur 18 mois, suivi nutritionnel, formation cantinières.",
    exigences: ["ONG enregistrée","Expérience logistique alimentaire"],
    documents: ["PADOR","Cadre logique","Budget"],
    source: "https://webgate.ec.europa.eu/europeaid/online-services/",
  },
  {
    id: "ao-012",
    titre: "Fourniture de 50 000 tablettes pédagogiques",
    bailleur: "AFD",
    pays: "Sénégal",
    secteur: "Education",
    type: "Fournitures",
    deadline: "2026-09-22T23:59:59.000Z",
    publication: "2026-06-08T00:00:00.000Z",
    montant: "2 800 000 000 FCFA",
    langue: "Français",
    contact: "tenders.sn@afd.fr",
    description: "Fourniture, déploiement et SAV de 50 000 tablettes Android préchargées de contenus pédagogiques.",
    exigences: ["Constructeur agréé","SAV national","Garantie 3 ans"],
    documents: ["Fiches techniques","Certifications CE"],
    source: "https://afd.dgmarket.com/",
  },
  {
    id: "ao-013",
    titre: "Forage de 150 puits d'eau potable en zone sahélienne",
    bailleur: "UNICEF",
    pays: "Mali",
    secteur: "Eau et Assainissement",
    type: "Travaux",
    deadline: "2026-07-18T23:59:59.000Z",
    publication: "2026-05-15T00:00:00.000Z",
    montant: "1 850 000 000 FCFA",
    langue: "Français",
    contact: "procurement-bko@unicef.org",
    description: "Forage et équipement de 150 puits avec pompes solaires dans Mopti et Ségou, formation comités de gestion.",
    exigences: ["Entreprise hydraulique","Capacité ≥ 50 forages/an"],
    documents: ["Caution 2%","Études hydrogéologiques","Planning"],
    source: "https://www.unicef.org/supply/",
  },
  {
    id: "ao-014",
    titre: "Construction d'adduction d'eau potable — Korhogo",
    bailleur: "BOAD",
    pays: "Côte d'Ivoire",
    secteur: "Eau et Assainissement",
    type: "Travaux",
    deadline: "2026-08-25T23:59:59.000Z",
    publication: "2026-06-03T00:00:00.000Z",
    montant: "6 400 000 000 FCFA",
    langue: "Français",
    contact: "passation@boad.org",
    description: "Construction d'un système d'adduction d'eau potable pour 250 000 habitants de Korhogo et environs.",
    exigences: ["Entreprise TP classée ≥ T5","Référence en adduction d'eau"],
    documents: ["Cautionnement 3%","Dossier technique","Planning"],
    source: "https://www.boad.org/appels-offres/",
  },
  {
    id: "ao-015",
    titre: "Appui institutionnel à la cour des comptes",
    bailleur: "UE",
    pays: "Sénégal",
    secteur: "Gouvernance",
    type: "Consulting",
    deadline: "2026-09-05T23:59:59.000Z",
    publication: "2026-06-12T00:00:00.000Z",
    montant: "290 000 000 FCFA",
    langue: "Français",
    contact: "delegation-senegal@eeas.europa.eu",
    description: "Renforcement des capacités de la Cour des Comptes : audits, contrôle juridictionnel, digitalisation.",
    exigences: ["Cabinet d'audit international","Expérience institutionnelle"],
    documents: ["Offre technique","Offre financière","CV experts"],
    source: "https://webgate.ec.europa.eu/europeaid/online-services/",
  },
  {
    id: "ao-016",
    titre: "Programme de santé maternelle — 60 maternités",
    bailleur: "USAID",
    pays: "Niger",
    secteur: "Santé",
    type: "Services",
    deadline: "2026-08-15T23:59:59.000Z",
    publication: "2026-05-28T00:00:00.000Z",
    montant: "2 300 000 000 FCFA",
    langue: "Français",
    contact: "procurement-niger@usaid.gov",
    description: "Renforcement de 60 maternités rurales : équipements, formation sages-femmes, suivi prénatal.",
    exigences: ["ONG internationale","Expérience santé maternelle ≥ 10 ans"],
    documents: ["Cadre logique","Budget détaillé","Lettre d'intention"],
    source: "https://www.usaid.gov/work-with-us/procurement",
  },
  {
    id: "ao-017",
    titre: "Étude diagnostique du secteur cotonnier",
    bailleur: "BAD",
    pays: "Burkina Faso",
    secteur: "Agriculture",
    type: "Consulting",
    deadline: "2026-07-20T23:59:59.000Z",
    publication: "2026-05-22T00:00:00.000Z",
    montant: "210 000 000 FCFA",
    langue: "Français",
    contact: "tenders@afdb.org",
    description: "Diagnostic complet de la filière coton burkinabè et recommandations stratégiques.",
    exigences: ["Cabinet agro-économique","Expérience filière coton"],
    documents: ["Note méthodologique","CV","Budget"],
    source: "https://www.afdb.org/en/projects-and-operations/procurement",
  },
  {
    id: "ao-018",
    titre: "Construction de 4 ponts modulaires — Région du Centre",
    bailleur: "BM",
    pays: "Mali",
    secteur: "Infrastructure",
    type: "Travaux",
    deadline: "2026-09-08T23:59:59.000Z",
    publication: "2026-06-01T00:00:00.000Z",
    montant: "3 200 000 000 FCFA",
    langue: "Français",
    contact: "procurement-mali@worldbank.org",
    description: "Construction de 4 ponts modulaires sur axes prioritaires de désenclavement.",
    exigences: ["Classe T4","Référence ouvrages d'art"],
    documents: ["Cautionnement 2%","Planning","Méthodologie"],
    source: "https://www.worldbank.org/en/projects-operations/products-and-services/brief/procurement-new-framework",
  },
  {
    id: "ao-019",
    titre: "Plateforme e-gouvernement — Portail des services publics",
    bailleur: "PNUD",
    pays: "Togo",
    secteur: "Numérique",
    type: "Services",
    deadline: "2026-08-10T23:59:59.000Z",
    publication: "2026-05-19T00:00:00.000Z",
    montant: "920 000 000 FCFA",
    langue: "Français",
    contact: "procurement.tg@undp.org",
    description: "Conception et développement d'un portail unifié des services publics togolais.",
    exigences: ["Expertise développement web","Sécurité OWASP","Hébergement souverain"],
    documents: ["Maquettes","Architecture technique","Offre financière"],
    source: "https://procurement-notices.undp.org/",
  },
  {
    id: "ao-020",
    titre: "Reforestation de 5 000 hectares — Bassin du Niger",
    bailleur: "GIZ",
    pays: "Niger",
    secteur: "Environnement",
    type: "Services",
    deadline: "2026-09-25T23:59:59.000Z",
    publication: "2026-06-14T00:00:00.000Z",
    montant: "1 750 000 000 FCFA",
    langue: "Français",
    contact: "tenders-niger@giz.de",
    description: "Programme de reforestation participative avec communautés locales et suivi satellitaire.",
    exigences: ["ONG environnementale","Expérience SIG"],
    documents: ["Méthodologie","Budget","Plan communautaire"],
    source: "https://www.giz.de/en/worldwide/333.html",
  },
  {
    id: "ao-021",
    titre: "Audit énergétique de 30 bâtiments publics",
    bailleur: "AFD",
    pays: "Bénin",
    secteur: "Environnement",
    type: "Consulting",
    deadline: "2026-07-08T23:59:59.000Z",
    publication: "2026-05-05T00:00:00.000Z",
    montant: "140 000 000 FCFA",
    langue: "Français",
    contact: "tenders.bj@afd.fr",
    description: "Audit énergétique complet et plan de rénovation pour 30 bâtiments administratifs.",
    exigences: ["Bureau d'études énergétique","Certifications ISO 50001"],
    documents: ["Méthodologie","CV","Offre financière"],
    source: "https://afd.dgmarket.com/",
  },
  {
    id: "ao-022",
    titre: "Fourniture de matériel médical — 25 hôpitaux régionaux",
    bailleur: "UNICEF",
    pays: "Burkina Faso",
    secteur: "Santé",
    type: "Fournitures",
    deadline: "2026-08-18T23:59:59.000Z",
    publication: "2026-06-04T00:00:00.000Z",
    montant: "2 150 000 000 FCFA",
    langue: "Français",
    contact: "procurement-oua@unicef.org",
    description: "Acquisition et livraison d'équipements médicaux (échographes, monitors, incubateurs) pour 25 hôpitaux.",
    exigences: ["Distributeur agréé","Certifications CE/FDA","SAV ≥ 5 ans"],
    documents: ["Fiches techniques","Plan logistique"],
    source: "https://www.unicef.org/supply/",
  },
  {
    id: "ao-023",
    titre: "Construction d'un marché moderne à Conakry",
    bailleur: "BOAD",
    pays: "Guinée",
    secteur: "Infrastructure",
    type: "Travaux",
    deadline: "2026-09-12T23:59:59.000Z",
    publication: "2026-06-06T00:00:00.000Z",
    montant: "4 800 000 000 FCFA",
    langue: "Français",
    contact: "passation@boad.org",
    description: "Construction d'un marché de 8 000 m² avec parkings, chambres froides et système de gestion des déchets.",
    exigences: ["Classe T5","Référence marchés urbains"],
    documents: ["Cautionnement 3%","Dossier technique","Planning"],
    source: "https://www.boad.org/appels-offres/",
  },
  {
    id: "ao-024",
    titre: "Élaboration du plan national d'adaptation climatique",
    bailleur: "BM",
    pays: "Ghana",
    secteur: "Environnement",
    type: "Consulting",
    deadline: "2026-08-22T23:59:59.000Z",
    publication: "2026-05-26T00:00:00.000Z",
    montant: "380 000 000 FCFA",
    langue: "Anglais",
    contact: "procurement-ghana@worldbank.org",
    description: "Élaboration du PNA-Climat avec scénarisation, modélisation et plan d'action sectoriel.",
    exigences: ["Bureau international climatique","Expertise GIEC"],
    documents: ["Note méthodologique","CV","Offre financière"],
    source: "https://www.worldbank.org/en/projects-operations/products-and-services/brief/procurement-new-framework",
  },
  {
    id: "ao-025",
    titre: "Programme d'alphabétisation fonctionnelle des femmes rurales",
    bailleur: "USAID",
    pays: "Mali",
    secteur: "Education",
    type: "Services",
    deadline: "2026-07-22T23:59:59.000Z",
    publication: "2026-05-12T00:00:00.000Z",
    montant: "680 000 000 FCFA",
    langue: "Français",
    contact: "procurement-mali@usaid.gov",
    description: "Alphabétisation de 25 000 femmes rurales sur 24 mois avec composante AGR.",
    exigences: ["ONG alphabétisation","Réseau ≥ 5 régions"],
    documents: ["Cadre logique","Budget","CV équipe"],
    source: "https://www.usaid.gov/work-with-us/procurement",
  },
  {
    id: "ao-026",
    titre: "Construction d'un data center souverain",
    bailleur: "Gouvernement",
    pays: "Sénégal",
    secteur: "Numérique",
    type: "Travaux",
    deadline: "2026-09-18T23:59:59.000Z",
    publication: "2026-06-09T00:00:00.000Z",
    montant: "8 500 000 000 FCFA",
    langue: "Français",
    contact: "contact@armp.sn",
    description: "Construction et équipement d'un data center Tier III à Diamniadio.",
    exigences: ["Consortium TP + IT","Certification Uptime Institute"],
    documents: ["Cautionnement 3%","Architecture technique","Planning"],
    source: "https://www.armp.sn/",
  },
  {
    id: "ao-027",
    titre: "Réhabilitation du réseau d'assainissement de Cotonou",
    bailleur: "BAD",
    pays: "Bénin",
    secteur: "Eau et Assainissement",
    type: "Travaux",
    deadline: "2026-08-28T23:59:59.000Z",
    publication: "2026-05-31T00:00:00.000Z",
    montant: "5 600 000 000 FCFA",
    langue: "Français",
    contact: "tenders-benin@afdb.org",
    description: "Réhabilitation et extension de 35 km de réseaux d'assainissement à Cotonou.",
    exigences: ["Entreprise hydraulique classée ≥ T5","Référence assainissement urbain"],
    documents: ["Caution 3%","Méthodologie","Planning"],
    source: "https://www.afdb.org/en/projects-and-operations/procurement",
  },
  {
    id: "ao-028",
    titre: "Sélection d'un cabinet pour l'audit des finances publiques",
    bailleur: "UE",
    pays: "Mauritanie",
    secteur: "Gouvernance",
    type: "Consulting",
    deadline: "2026-07-15T23:59:59.000Z",
    publication: "2026-05-10T00:00:00.000Z",
    montant: "260 000 000 FCFA",
    langue: "Français",
    contact: "delegation-mauritanie@eeas.europa.eu",
    description: "Audit des finances publiques et appui à la réforme PFM.",
    exigences: ["Cabinet d'audit international","Expérience PFM"],
    documents: ["Offre technique","Offre financière"],
    source: "https://webgate.ec.europa.eu/europeaid/online-services/",
  },
  {
    id: "ao-029",
    titre: "Distribution de moustiquaires imprégnées — 1,2 M unités",
    bailleur: "UNICEF",
    pays: "Côte d'Ivoire",
    secteur: "Santé",
    type: "Fournitures",
    deadline: "2026-06-28T23:59:59.000Z",
    publication: "2026-04-30T00:00:00.000Z",
    montant: "1 400 000 000 FCFA",
    langue: "Français",
    contact: "procurement-abj@unicef.org",
    description: "Acquisition et distribution de 1,2 million de moustiquaires LLIN dans 8 régions.",
    exigences: ["Fournisseur WHOPES","Plan de distribution"],
    documents: ["Fiches techniques","Logistique"],
    source: "https://www.unicef.org/supply/",
  },
  {
    id: "ao-030",
    titre: "Mise en place d'un système d'irrigation goutte-à-goutte — 2 000 ha",
    bailleur: "BOAD",
    pays: "Burkina Faso",
    secteur: "Agriculture",
    type: "Travaux",
    deadline: "2026-09-02T23:59:59.000Z",
    publication: "2026-06-07T00:00:00.000Z",
    montant: "2 950 000 000 FCFA",
    langue: "Français",
    contact: "passation@boad.org",
    description: "Installation de systèmes d'irrigation moderne sur 2 000 ha au profit de 5 000 producteurs.",
    exigences: ["Entreprise hydroagricole","Référence ≥ 1 000 ha"],
    documents: ["Caution 2%","Dossier technique","Planning"],
    source: "https://www.boad.org/appels-offres/",
  },
  {
    id: "ao-031",
    titre: "Construction de 6 marchés de gros agricoles",
    bailleur: "AFD",
    pays: "Côte d'Ivoire",
    secteur: "Agriculture",
    type: "Travaux",
    deadline: "2026-08-08T23:59:59.000Z",
    publication: "2026-05-21T00:00:00.000Z",
    montant: "4 100 000 000 FCFA",
    langue: "Français",
    contact: "tenders.ci@afd.fr",
    description: "Construction de 6 marchés de gros avec chambres froides et plateformes logistiques.",
    exigences: ["Classe T4","Référence infrastructures rurales"],
    documents: ["Caution 2%","Méthodologie","Planning"],
    source: "https://afd.dgmarket.com/",
  },
  {
    id: "ao-032",
    titre: "Mise en œuvre du Système Intégré de Gestion des Finances Publiques",
    bailleur: "BM",
    pays: "Togo",
    secteur: "Numérique",
    type: "Services",
    deadline: "2026-09-20T23:59:59.000Z",
    publication: "2026-06-11T00:00:00.000Z",
    montant: "1 600 000 000 FCFA",
    langue: "Français",
    contact: "procurement-togo@worldbank.org",
    description: "Déploiement d'un SIGFP couvrant budget, exécution, comptabilité et reporting.",
    exigences: ["Éditeur ERP public","Référence SIGFP en Afrique"],
    documents: ["Offre technique","Offre financière","CV"],
    source: "https://www.worldbank.org/en/projects-operations/products-and-services/brief/procurement-new-framework",
  },
  {
    id: "ao-033",
    titre: "Programme de protection sociale — 100 000 ménages",
    bailleur: "PNUD",
    pays: "Mauritanie",
    secteur: "Gouvernance",
    type: "Services",
    deadline: "2026-08-05T23:59:59.000Z",
    publication: "2026-05-17T00:00:00.000Z",
    montant: "1 250 000 000 FCFA",
    langue: "Français",
    contact: "procurement.mr@undp.org",
    description: "Mise en place d'un programme de transferts monétaires pour 100 000 ménages vulnérables.",
    exigences: ["ONG internationale","Expérience CCT"],
    documents: ["Cadre logique","Budget","CV équipe"],
    source: "https://procurement-notices.undp.org/",
  },
  {
    id: "ao-034",
    titre: "Formation de 800 enseignants en pédagogie numérique",
    bailleur: "GIZ",
    pays: "Togo",
    secteur: "Education",
    type: "Services",
    deadline: "2026-07-25T23:59:59.000Z",
    publication: "2026-05-14T00:00:00.000Z",
    montant: "420 000 000 FCFA",
    langue: "Français",
    contact: "tenders-togo@giz.de",
    description: "Formation de 800 enseignants du secondaire à l'intégration du numérique en classe.",
    exigences: ["Cabinet en pédagogie","Expérience formation enseignants"],
    documents: ["Méthodologie","CV","Budget"],
    source: "https://www.giz.de/en/worldwide/333.html",
  },
  {
    id: "ao-035",
    titre: "Construction de 3 stations de traitement des eaux usées",
    bailleur: "BOAD",
    pays: "Sénégal",
    secteur: "Eau et Assainissement",
    type: "Travaux",
    deadline: "2026-09-28T23:59:59.000Z",
    publication: "2026-06-13T00:00:00.000Z",
    montant: "7 200 000 000 FCFA",
    langue: "Français",
    contact: "passation@boad.org",
    description: "Construction de 3 STEP de 15 000 m³/jour à Thiès, Mbour et Saint-Louis.",
    exigences: ["Classe T5","Référence STEP"],
    documents: ["Caution 3%","Dossier technique","EIES"],
    source: "https://www.boad.org/appels-offres/",
  },
  {
    id: "ao-036",
    titre: "Acquisition de véhicules tout-terrain — 80 unités",
    bailleur: "USAID",
    pays: "Burkina Faso",
    secteur: "Infrastructure",
    type: "Fournitures",
    deadline: "2026-07-30T23:59:59.000Z",
    publication: "2026-05-23T00:00:00.000Z",
    montant: "1 350 000 000 FCFA",
    langue: "Français",
    contact: "procurement-burkina@usaid.gov",
    description: "Acquisition de 80 véhicules 4x4 pour missions humanitaires en zones rurales.",
    exigences: ["Distributeur agréé","SAV national","Garantie 3 ans"],
    documents: ["Fiches techniques","Plan SAV"],
    source: "https://www.usaid.gov/work-with-us/procurement",
  },
  {
    id: "ao-037",
    titre: "Élaboration de la stratégie nationale d'inclusion financière",
    bailleur: "BAD",
    pays: "Guinée",
    secteur: "Gouvernance",
    type: "Consulting",
    deadline: "2026-08-02T23:59:59.000Z",
    publication: "2026-05-16T00:00:00.000Z",
    montant: "185 000 000 FCFA",
    langue: "Français",
    contact: "tenders@afdb.org",
    description: "Diagnostic et formulation d'une stratégie nationale d'inclusion financière à horizon 2030.",
    exigences: ["Cabinet finance inclusive","Expérience UEMOA/CEDEAO"],
    documents: ["Note méthodologique","CV","Budget"],
    source: "https://www.afdb.org/en/projects-and-operations/procurement",
  },
  {
    id: "ao-038",
    titre: "Réhabilitation de 25 écoles primaires post-conflit",
    bailleur: "UNICEF",
    pays: "Mali",
    secteur: "Education",
    type: "Travaux",
    deadline: "2026-09-30T23:59:59.000Z",
    publication: "2026-06-15T00:00:00.000Z",
    montant: "980 000 000 FCFA",
    langue: "Français",
    contact: "procurement-bko@unicef.org",
    description: "Réhabilitation de 25 écoles primaires dans le Centre Mali avec kit scolaire et eau potable.",
    exigences: ["Entreprise TP ≥ T3","Capacité travaux en zone fragile"],
    documents: ["Caution 2%","Planning","Méthodologie"],
    source: "https://www.unicef.org/supply/",
  },
  {
    id: "ao-039",
    titre: "Système d'information sanitaire national",
    bailleur: "UE",
    pays: "Bénin",
    secteur: "Santé",
    type: "Services",
    deadline: "2026-08-14T23:59:59.000Z",
    publication: "2026-05-27T00:00:00.000Z",
    montant: "1 050 000 000 FCFA",
    langue: "Français",
    contact: "delegation-benin@eeas.europa.eu",
    description: "Conception et déploiement du SIS national avec DHIS2 et formation des 600 utilisateurs.",
    exigences: ["Expertise DHIS2","Référence SIS en Afrique"],
    documents: ["Offre technique","Offre financière","CV"],
    source: "https://webgate.ec.europa.eu/europeaid/online-services/",
  },
  {
    id: "ao-040",
    titre: "Construction d'une centrale solaire de 25 MWc",
    bailleur: "AFD",
    pays: "Mauritanie",
    secteur: "Environnement",
    type: "Travaux",
    deadline: "2026-09-14T23:59:59.000Z",
    publication: "2026-06-02T00:00:00.000Z",
    montant: "9 800 000 000 FCFA",
    langue: "Français",
    contact: "tenders.mr@afd.fr",
    description: "EPC d'une centrale solaire photovoltaïque de 25 MWc avec poste d'évacuation.",
    exigences: ["EPC solaire ≥ 50 MWc","Référence Afrique de l'Ouest"],
    documents: ["Caution 3%","Études techniques","Planning"],
    source: "https://afd.dgmarket.com/",
  },
  {
    id: "ao-041",
    titre: "Plan directeur d'urbanisme de Niamey",
    bailleur: "BM",
    pays: "Niger",
    secteur: "Infrastructure",
    type: "Consulting",
    deadline: "2026-08-11T23:59:59.000Z",
    publication: "2026-05-24T00:00:00.000Z",
    montant: "340 000 000 FCFA",
    langue: "Français",
    contact: "procurement-niger@worldbank.org",
    description: "Élaboration du plan directeur d'urbanisme de Niamey à horizon 2045.",
    exigences: ["Cabinet urbanisme international","SIG urbain"],
    documents: ["Note méthodologique","CV","Budget"],
    source: "https://www.worldbank.org/en/projects-operations/products-and-services/brief/procurement-new-framework",
  },
  {
    id: "ao-042",
    titre: "Programme d'appui aux startups numériques",
    bailleur: "PNUD",
    pays: "Ghana",
    secteur: "Numérique",
    type: "Services",
    deadline: "2026-07-10T23:59:59.000Z",
    publication: "2026-05-04T00:00:00.000Z",
    montant: "560 000 000 FCFA",
    langue: "Anglais",
    contact: "procurement.gh@undp.org",
    description: "Programme d'incubation et de financement pour 100 startups numériques ghanéennes.",
    exigences: ["Incubateur expérimenté","Réseau VC"],
    documents: ["Méthodologie","CV équipe","Budget"],
    source: "https://procurement-notices.undp.org/",
  },
  {
    id: "ao-043",
    titre: "Approvisionnement en intrants agricoles — 30 000 producteurs",
    bailleur: "BOAD",
    pays: "Niger",
    secteur: "Agriculture",
    type: "Fournitures",
    deadline: "2026-08-26T23:59:59.000Z",
    publication: "2026-05-29T00:00:00.000Z",
    montant: "1 900 000 000 FCFA",
    langue: "Français",
    contact: "passation@boad.org",
    description: "Fourniture de semences améliorées, engrais et petits équipements pour 30 000 producteurs.",
    exigences: ["Distributeur agréé","Capacité logistique"],
    documents: ["Fiches produits","Plan distribution"],
    source: "https://www.boad.org/appels-offres/",
  },
  {
    id: "ao-044",
    titre: "Audit organisationnel du Ministère de l'Économie",
    bailleur: "Gouvernement",
    pays: "Mali",
    secteur: "Gouvernance",
    type: "Consulting",
    deadline: "2026-07-04T23:59:59.000Z",
    publication: "2026-05-01T00:00:00.000Z",
    montant: "145 000 000 FCFA",
    langue: "Français",
    contact: "contact@dgmp.gouv.ml",
    description: "Audit organisationnel et fonctionnel du Ministère de l'Économie et des Finances.",
    exigences: ["Cabinet conseil","Expérience administration publique"],
    documents: ["Note méthodologique","CV","Offre financière"],
    source: "https://www.dgmp.gov.ml/",
  },
  {
    id: "ao-045",
    titre: "Construction de 200 km de lignes électriques MT/BT",
    bailleur: "BAD",
    pays: "Sénégal",
    secteur: "Infrastructure",
    type: "Travaux",
    deadline: "2026-09-08T23:59:59.000Z",
    publication: "2026-06-03T00:00:00.000Z",
    montant: "6 800 000 000 FCFA",
    langue: "Français",
    contact: "tenders-senegal@afdb.org",
    description: "Construction de 200 km de lignes électriques moyenne et basse tension pour l'électrification rurale.",
    exigences: ["Entreprise électrique ≥ T5","Référence MT/BT ≥ 100 km"],
    documents: ["Caution 3%","Dossier technique","Planning"],
    source: "https://www.afdb.org/en/projects-and-operations/procurement",
  },
  {
    id: "ao-046",
    titre: "Programme WASH dans 80 écoles primaires",
    bailleur: "UNICEF",
    pays: "Togo",
    secteur: "Eau et Assainissement",
    type: "Services",
    deadline: "2026-08-08T23:59:59.000Z",
    publication: "2026-05-20T00:00:00.000Z",
    montant: "640 000 000 FCFA",
    langue: "Français",
    contact: "procurement-lome@unicef.org",
    description: "Mise en place d'infrastructures WASH (eau, hygiène, latrines) dans 80 écoles primaires.",
    exigences: ["ONG WASH","Référence ≥ 50 écoles"],
    documents: ["Méthodologie","Budget","CV"],
    source: "https://www.unicef.org/supply/",
  },
  {
    id: "ao-047",
    titre: "Mise en place d'un système de surveillance épidémiologique",
    bailleur: "USAID",
    pays: "Ghana",
    secteur: "Santé",
    type: "Services",
    deadline: "2026-09-04T23:59:59.000Z",
    publication: "2026-06-10T00:00:00.000Z",
    montant: "890 000 000 FCFA",
    langue: "Anglais",
    contact: "procurement-ghana@usaid.gov",
    description: "Déploiement d'un système digital de surveillance épidémiologique dans 16 régions.",
    exigences: ["Expertise santé publique","DHIS2 ou équivalent"],
    documents: ["Offre technique","Offre financière","CV"],
    source: "https://www.usaid.gov/work-with-us/procurement",
  },
  {
    id: "ao-048",
    titre: "Étude d'impact environnemental — Mine d'or",
    bailleur: "GIZ",
    pays: "Guinée",
    secteur: "Environnement",
    type: "Consulting",
    deadline: "2026-07-26T23:59:59.000Z",
    publication: "2026-05-13T00:00:00.000Z",
    montant: "265 000 000 FCFA",
    langue: "Français",
    contact: "tenders-guinea@giz.de",
    description: "EIES complète pour un projet minier en Haute Guinée.",
    exigences: ["Bureau EIES agréé","Expérience secteur minier"],
    documents: ["Note méthodologique","CV","Budget"],
    source: "https://www.giz.de/en/worldwide/333.html",
  },
  {
    id: "ao-049",
    titre: "Construction d'un complexe sportif national",
    bailleur: "Gouvernement",
    pays: "Côte d'Ivoire",
    secteur: "Infrastructure",
    type: "Travaux",
    deadline: "2026-09-25T23:59:59.000Z",
    publication: "2026-06-12T00:00:00.000Z",
    montant: "12 400 000 000 FCFA",
    langue: "Français",
    contact: "contact@anrmp.ci",
    description: "Construction d'un complexe sportif de 40 000 places avec annexes.",
    exigences: ["Classe T5","Référence stade ≥ 20 000 places"],
    documents: ["Caution 3%","Dossier technique","Planning"],
    source: "https://www.anrmp.ci/",
  },
  {
    id: "ao-050",
    titre: "Fourniture de groupes électrogènes pour 50 hôpitaux",
    bailleur: "BOAD",
    pays: "Mali",
    secteur: "Santé",
    type: "Fournitures",
    deadline: "2026-08-16T23:59:59.000Z",
    publication: "2026-05-25T00:00:00.000Z",
    montant: "1 720 000 000 FCFA",
    langue: "Français",
    contact: "passation@boad.org",
    description: "Acquisition, livraison et installation de 50 groupes électrogènes de 100-250 kVA pour hôpitaux.",
    exigences: ["Distributeur agréé","SAV national","Garantie 2 ans"],
    documents: ["Fiches techniques","Plan SAV"],
    source: "https://www.boad.org/appels-offres/",
  },
  {
    id: "ao-051",
    titre: "Programme d'agroécologie — 10 000 producteurs",
    bailleur: "UE",
    pays: "Burkina Faso",
    secteur: "Agriculture",
    type: "Services",
    deadline: "2026-07-14T23:59:59.000Z",
    publication: "2026-05-06T00:00:00.000Z",
    montant: "1 480 000 000 FCFA",
    langue: "Français",
    contact: "delegation-burkina@eeas.europa.eu",
    description: "Accompagnement de 10 000 producteurs en pratiques agroécologiques sur 36 mois.",
    exigences: ["ONG agroécologie","Présence terrain ≥ 5 régions"],
    documents: ["Cadre logique","Budget","CV"],
    source: "https://webgate.ec.europa.eu/europeaid/online-services/",
  },
  {
    id: "ao-052",
    titre: "Déploiement de la fibre optique — 1 200 km",
    bailleur: "BM",
    pays: "Bénin",
    secteur: "Numérique",
    type: "Travaux",
    deadline: "2026-09-16T23:59:59.000Z",
    publication: "2026-06-04T00:00:00.000Z",
    montant: "8 200 000 000 FCFA",
    langue: "Français",
    contact: "procurement-benin@worldbank.org",
    description: "Déploiement de 1 200 km de fibre optique reliant 22 chefs-lieux de communes.",
    exigences: ["Opérateur télécom ou EPC fibre","Référence ≥ 500 km"],
    documents: ["Caution 3%","Dossier technique","Planning"],
    source: "https://www.worldbank.org/en/projects-operations/products-and-services/brief/procurement-new-framework",
  },
  {
    id: "ao-053",
    titre: "Assistance technique à l'autorité de régulation des marchés publics",
    bailleur: "AFD",
    pays: "Niger",
    secteur: "Gouvernance",
    type: "Consulting",
    deadline: "2026-08-19T23:59:59.000Z",
    publication: "2026-05-30T00:00:00.000Z",
    montant: "220 000 000 FCFA",
    langue: "Français",
    contact: "tenders.ne@afd.fr",
    description: "Renforcement institutionnel de l'ARMP : digitalisation, formations, manuel de procédures.",
    exigences: ["Cabinet gouvernance","Expérience marchés publics"],
    documents: ["Note méthodologique","CV","Offre financière"],
    source: "https://afd.dgmarket.com/",
  },
  {
    id: "ao-054",
    titre: "Construction de 4 000 logements sociaux",
    bailleur: "BAD",
    pays: "Côte d'Ivoire",
    secteur: "Infrastructure",
    type: "Travaux",
    deadline: "2026-09-30T23:59:59.000Z",
    publication: "2026-06-14T00:00:00.000Z",
    montant: "18 500 000 000 FCFA",
    langue: "Français",
    contact: "tenders-ci@afdb.org",
    description: "Construction de 4 000 logements sociaux à Abidjan et Yamoussoukro avec viabilisation.",
    exigences: ["Promoteur ≥ 2 000 logements","Capacité financière confirmée"],
    documents: ["Caution 3%","Dossier technique","Planning"],
    source: "https://www.afdb.org/en/projects-and-operations/procurement",
  },
  {
    id: "ao-055",
    titre: "Renforcement du système de cantines scolaires",
    bailleur: "UNICEF",
    pays: "Niger",
    secteur: "Education",
    type: "Services",
    deadline: "2026-07-02T23:59:59.000Z",
    publication: "2026-04-29T00:00:00.000Z",
    montant: "720 000 000 FCFA",
    langue: "Français",
    contact: "procurement-niamey@unicef.org",
    description: "Approvisionnement de 1 200 cantines scolaires sur 18 mois.",
    exigences: ["ONG sécurité alimentaire","Capacité logistique"],
    documents: ["Cadre logique","Budget","Plan logistique"],
    source: "https://www.unicef.org/supply/",
  },
  {
    id: "ao-056",
    titre: "Plateforme e-santé pour les hôpitaux de district",
    bailleur: "PNUD",
    pays: "Sénégal",
    secteur: "Numérique",
    type: "Services",
    deadline: "2026-08-23T23:59:59.000Z",
    publication: "2026-05-22T00:00:00.000Z",
    montant: "680 000 000 FCFA",
    langue: "Français",
    contact: "procurement.sn@undp.org",
    description: "Développement d'une plateforme e-santé interopérable pour 45 hôpitaux de district.",
    exigences: ["Éditeur santé numérique","Standards HL7/FHIR"],
    documents: ["Offre technique","Offre financière","CV"],
    source: "https://procurement-notices.undp.org/",
  }
];

export const PAYS_LIST: Pays[] = [
  "Sénégal",
  "Côte d'Ivoire",
  "Mali",
  "Burkina Faso",
  "Ghana",
  "Guinée",
  "Bénin",
  "Togo",
  "Niger",
  "Mauritanie",
];

export const SECTEUR_LIST: Secteur[] = [
  "Santé",
  "Education",
  "Infrastructure",
  "Agriculture",
  "Numérique",
  "Environnement",
  "Gouvernance",
  "Eau et Assainissement",
  "Autre",
];

export const BAILLEUR_LIST: Bailleur[] = [
  "BM",
  "BAD",
  "PNUD",
  "UE",
  "AFD",
  "GIZ",
  "USAID",
  "UNICEF",
  "BOAD",
  "Gouvernement",
  "Autre",
];

export const TYPE_LIST: TypeMarche[] = ["Travaux", "Services", "Fournitures", "Consulting"];

// Handles ISO strings AND Unix timestamps in seconds (Supabase may return either)
const parseDate = (val: string | number): Date => {
  if (typeof val === "number") {
    // If timestamp is in seconds (Unix), convert to ms
    return new Date(val < 1e10 ? val * 1000 : val);
  }
  const d = new Date(val);
  // If year < 2000, assume it's a Unix timestamp stored as string
  if (d.getFullYear() < 2000) {
    const num = Number(val);
    if (!isNaN(num)) return new Date(num < 1e10 ? num * 1000 : num);
  }
  return d;
};

export const daysUntil = (iso: string) => {
  const ms = parseDate(iso).getTime() - Date.now();
  return Math.ceil(ms / (1000 * 60 * 60 * 24));
};

export const formatDate = (iso: string) =>
  parseDate(iso).toLocaleDateString("fr-FR", { day: "2-digit", month: "short", year: "numeric" });